project:
  type: website
  resources:
    - img/*
  render:
    - "*.md"
    - "*.qmd"

website:
  repo-url: https://github.com/soil-data-of-africa
  repo-subdir: src
  repo-actions:
    - issue
  page-footer:
    left:
    - text: AUSO
  title: "AUSO"
  search: true
  navbar:
    pinned: true
    logo: ./img/logo.png
    right:
      - text: About AUSO
        file: index.md#about-auso
      - text: Who it's for
        file: index.md#who-is-auso-for
      - text: Dashboard
        file: dashboard.qmd
      - text: ASDAC Database
        file: asdac/index.md
      - text: Resources
        file: resources.md
      - text: Contact
        file: contact.md
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: ASDAC Home
        file: asdac/index.md
      - text: Documents
        file: asdac/documents.md
      - text: Procedures
        file: asdac/procedures.md
      - text: Data platforms
        file: asdac/data-platforms.md
      - text: Code Repositories
        file: asdac/code-repositories.md
      - text: Videos
        file: asdac/videos.md
      - text: Tech manuals
        file: asdac/tech-manuals.md
      - text: SIS software
        file: asdac/sis-software.md
format:
  html:
    page-layout: full
    theme: 
      - flatly
      - styles.scss
    filters:
      - ./filters/collapse/_extensions/collapse/collapse.lua
      - ./filters/page-section/_extensions/page-section/page-section.lua
    shortcodes: 
      - ./shortcodes/icon-link/_extensions/icon-link/icon-link.lua
